### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Yanis002** [Yanis42/Sandy#1]
- [ ] Show a list of every splits
- [ ] Add a per-split configuration for flags
- [ ] Add a rollback feature that will restore the original names if something goes wrong
- [ ] Remove the mask flag as it's not needed anymore
- [ ] Fix the issue where having a dummy for a split name that starts with a letter before D puts the dummy after the real split
- [ ] Preview how the folder will look like (?)
- [ ] Web version (?)
